#!/bin/bash
# ============================================================
# SLURM Job Template for Multi-GPU Training
# Generated by the Autonomous Experiment Orchestrator
# ============================================================

#SBATCH --job-name=transformer_300m
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gpus-per-node=4
#SBATCH --cpus-per-gpu=4
#SBATCH --mem-per-gpu=32G
#SBATCH --time=24:00:00
#SBATCH --output=logs/slurm_%j.log
#SBATCH --error=logs/slurm_%j.err
#SBATCH --requeue

# --- Environment ---
source activate sae 2>/dev/null || conda activate sae

export NCCL_DEBUG=WARN
export NCCL_SOCKET_IFNAME=eth0
export OMP_NUM_THREADS=4

# --- Job Info ---
echo "============================================"
echo "Job ID:     $SLURM_JOB_ID"
echo "Node:       $(hostname)"
echo "Date:       $(date)"
echo "GPUs:       $CUDA_VISIBLE_DEVICES"
echo "============================================"
nvidia-smi

# --- Launch Orchestrator ---
cd $SLURM_SUBMIT_DIR

python run_orchestrator.py \
    --config configs/default_config.yaml \
    --num_gpus 4

echo "Job $SLURM_JOB_ID finished at $(date) with exit code $?"
